chateau.wad
cs_bdog.wad
cs_cbble.wad
cs_havana.WAD
cs_office.wad
cstrike.wad
de_aztec.wad
de_piranesi.wad
de_vertigo.wad
halflife.wad
itsitaly.wad
models/palmtree.mdl
n0th1ng.wad
sound/de_torn/torn_AK-47.wav
sound/ze_BlackFTX_escape/Escape_Deff.wav
sound/ze_BlackFTX_escape/Music_Spawn_Esc.wav
sound/ze_BlackFTX_escape/WTF_Bomb_Exp.wav
sprites/glow01.spr
sprites/laserbeam.spr
torntextures.wad
tswad.wad